[tools]
dotnet = "9.0.101"
helm = "3.17.2"
k9s = "0.40.10"
kubectl = "1.32.3"
minikube = "latest"
node = "20"
"npm:supersetbot" = "0.5.43"
python = "3.13.2"
ripgrep = "14.1.1"
terraform = "1.9.8"
terraform-docs = "0.19.0"
usage = "latest"
